name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    # Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    # Cache FFmpeg apt package
    - name: Cache FFmpeg
      uses: actions/cache@v3
      id: cache-ffmpeg
      with:
        path: ~/ffmpeg-cache
        key: ${{ runner.os }}-ffmpeg-${{ hashFiles('~/.cache/apt/archives/ffmpeg*.deb') || 'not-exists' }}
        
    - name: Install FFmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        mkdir -p ~/ffmpeg-cache
        cd ~/ffmpeg-cache
        apt-get download ffmpeg
        sudo apt-get install -y ./ffmpeg*.deb
        
    - name: Install FFmpeg from cache
      if: steps.cache-ffmpeg.outputs.cache-hit == 'true'
      run: |
        sudo apt-get install -y ~/ffmpeg-cache/ffmpeg*.deb
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run tests
      env:
        FFMPEG_PATH: /usr/bin/ffmpeg
        FFPROBE_PATH: /usr/bin/ffprobe
      run: |
        pytest tests/ -v --cov=tests --cov-report=term-missing:skip-covered